name: Prototype01 of the opencare project
markdown: kramdown
baseurl: /OpenCarePrototype01
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-sitemap
  - jekyll-paginate
paginate: 10
paginate_path: /blog/page:num/
