name: MicroWebsite<br>Template
author: WeMake
markdown: kramdown
baseurl:
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "MicroWebsiteTemplate by opencarecc"
tagline: "This is the template for opencarecc websites"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "en"

# Facebook OpenGraph stuff
opengraph:
  title: "MicroWebsiteTemplate by opencarecc"
  url: "http://opencarecc.github.io/MicroWebsiteTemplate/"
  description: "This is the template for opencarecc websites"
  image_url: "http://opencarecc.github.io/MicroWebsiteTemplate/assets/OC-Logo-socials.png"

# Twitter Card stuff
twitter:
  site: "opencarecc MicroWebsiteTemplate"
  title: "MicroWebsiteTemplate by opencarecc"
  description: "This is the template for opencarecc websites"
  creator: "opencarecc"
  domain: "http://opencarecc.github.io/MicroWebsiteTemplate/"
  image_url: "http://opencarecc.github.io/MicroWebsiteTemplate/assets/OC-Logo-socials.png"
