name: Ritornello
author: WeMake
markdown: kramdown
baseurl:
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "Ritornello by WeMake"
tagline: "This is a tagline"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "it"

# Facebook OpenGraph stuff
opengraph:
  title: "Ritornello by WeMake"
  url: "http://opencarecc.github.io/MicroWebsiteTemplate/"
  description: "This is a tagline"
  image_url: "http://opencarecc.github.io/MicroWebsiteTemplate/assets/OC-Logo-socials.png"

# Twitter Card stuff
twitter:
  site: "Ritornello by WeMake"
  title: "Ritornello by WeMake"
  description: "This is a tagline"
  creator: "opencarecc"
  domain: "http://opencarecc.github.io/MicroWebsiteTemplate/"
  image_url: "http://opencarecc.github.io/MicroWebsiteTemplate/assets/OC-Logo-socials.png"
